# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Euler in Python
tagline:          'A Jekyll theme'
description:      'A website with the solutions to a few of the <a href="https://projecteuler.net/" target="_blank">Project Euler''s</a> challenges. Made with love by <a href="https://www.instagram.com/bruno.3s" target="_blank">@bruno.3s</a>'
# url:              http://hyde.getpoole.com
baseurl:          ""

author:
  name:           'Bruno Silva'
  url:            https://www.instagram.com/bruno.3s

version:          1.0

paginate:         5

github:
  repo:           https://github.com/bru1987/euler
repository:       euler/bru1987

disqus:
  shortname: eulerinpython